742a htmx for name select choice field
TOMToolkit/tom_base pull request #1004
Opened 2024-08-05 20:10 UTC by phycodurus

This PR removes the Submit button and make changing the target name_select ChoiceField update the target fields table:

1. HTMX attributes were added to the name_select ChoiceField
2. a GET method was added to the TargetMergeView - if it's an HTMX request triggered by a name_select ChoiceField change, then it updates the table by calling the inclusiontag directly to get it's context and rendering the partial with the new context and return that new HTML. The htmx attributes of the ChoiceField specify (via that hx-target attribute) that the #id_target_merge_fields HTML should be replace.
3. the #id_target_merge_fields property was assigned to the <table> in the target_fields.html partial.

2024-08-05 21:02 UTC, sglasberg requested changes
When I tried to run this I got an attribute error: 
`AttributeError: 'WSGIRequest' object has no attribute 'htmx'`

here is the traceback:
```
File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/tom_base/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/TOM_explore/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sglasberg/dev/tom_base/tom_targets/views.py", line 641, in get
    if request.htmx:
       ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'htmx'
```

2024-08-05 21:23 UTC, sglasberg requested changes
please add `django_htmx` to `pyproject.toml` so that we install this dependency 

Could you also please update `settings.tmpl` with the required intalled app and middleware

2024-08-06 15:52 UTC, phycodurus commented on tom_targets/views.py
> +            # decide which of pk1 or pk2 is primary (i.e. it matches name_select)
Same :-< (I see that now, but I'm pretty sure that was working (locally) before -- looking into it...)

2024-08-06 16:51 UTC, sglasberg requested changes
Looks pretty good

2024-08-06 16:51 UTC, sglasberg commented on tom_targets/templatetags/targets_extras.py
> +import logging
Logging is not currently used in `targets_extras` should we remove this until it is needed

2024-08-06 16:55 UTC, phycodurus commented on tom_targets/templatetags/targets_extras.py
> +import logging
Please leave this in.

2024-08-06 17:27 UTC, sglasberg approved these changes

2024-08-06 17:27 UTC, merged