742 manually link two targets as the same target and merge namesdatasets
TOMToolkit/tom_base pull request #1008
Opened 2024-08-08 23:08 UTC by sglasberg

I finished my project, but may add more depending on time.

2024-08-09 21:09 UTC, jchate6 requested changes
Mostly documentation stuff.

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/target_fields.html
> +</table>
Need a blank line and the end of the file

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/templatetags/targets_extras.py
> +    Make a list of tuples that combines the fields and values of the two targets.
describe the input for this method, Specifically what is expected from `target1` and `target2`

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/tests/tests.py
> +        # print(model_to_dict(self.st1))
Can remove this

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/tests/tests.py
> +        #  write a test that makes sure datum1 and datum3 are the only datums associated with self.st1 after the merge
We decided not to do this yet...

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/views.py
> +    def get_name_select_choices(self, pk1, pk2):
Short doc string about what this method does and what it's inputs/outputs should be.

2024-08-09 21:09 UTC, jchate6 commented on tom_targets/views.py
> +            if 'confirm' in request.POST:
comment here about what happens if confirm is in the request

2024-08-09 21:26 UTC, sglasberg commented on tom_targets/templates/tom_targets/partials/target_fields.html
Renamed to `target_merge_fields.html` will this break any of the code?

2024-08-09 21:33 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/target_fields.html
yes, you'll need to change the name in target_extras

2024-08-09 21:34 UTC, jchate6 commented on tom_targets/templatetags/targets_extras.py
> +@register.inclusion_tag('tom_targets/partials/target_fields.html')
This will need to be changed if target_fields is changed

2024-08-09 21:35 UTC, jchate6 commented on tom_targets/templatetags/targets_extras.py
> +def target_fields(target1, target2):
If you make this name more specific, you'll need to update line 12 in target_merge.html too.

2024-08-09 22:42 UTC, jchate6 commented
@sglasberg Please put back in the lines where you edit and save st1 and st2 in `test_merge_targets` the only thing we wanted to remove was the print statement.

2024-08-09 22:48 UTC, jchate6 requested changes
a few more things!

2024-08-09 22:48 UTC, jchate6 commented on tom_targets/merge.py
> +    """
Convert this from a doc string to 2 lines commented normally `#` instead of `""""`

2024-08-09 22:48 UTC, jchate6 commented on tom_targets/views.py
> +from tom_targets.templatetags.targets_extras import target_fields
this needs to be updated with the new name as well.

2024-08-09 22:50 UTC, jchate6 requested changes

2024-08-09 22:50 UTC, jchate6 commented on tom_targets/views.py
> +                'tom_targets/partials/target_fields.html',
Here too

2024-08-09 22:50 UTC, jchate6 commented on tom_targets/views.py
> +                context=target_fields(primary_target, secondary_target))
and here

2024-08-09 22:51 UTC, sglasberg commented on tom_targets/views.py
> +from tom_targets.templatetags.targets_extras import target_fields
flake is saying its unused should I delete this line

2024-08-09 23:05 UTC, jchate6 approved these changes

2024-08-12 17:51 UTC, phycodurus requested changes

2024-08-12 17:51 UTC, phycodurus commented on tom_targets/views.py
> +    def get_form_class(self):
This method is actually not necessary and could be deleted.

The reason is because the `form_class` is defined as a class variable (up on line #576) and the [super-class implementation](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/FormMixin/#get_form_class) returns that. So, the `form_class` could be define once and only once (DRY - don't repeat yourself principle at work here) up on line #576.

2024-08-13 22:01 UTC, phycodurus approved these changes

2024-08-13 22:42 UTC, merged