update docs with a brief description of AnonymousUser
TOMToolkit/tom_base pull request #1053
Opened 2024-09-30 09:49 UTC by jchate6

2024-10-14 15:51 UTC, rachel3834 approved these changes
Clear explanation, I think it covers everything users need to know.

2024-10-16 17:20 UTC, phycodurus requested changes

2024-10-16 17:20 UTC, phycodurus commented on docs/common/permissions.rst
> +When you first establish your TOM, ``django-guardian`` will create an ``AnonymousUser`` as the default user for the
Maybe this is the correct way to explain this in the context of Permissions, but I think it leaves out the role AnonymousUser plays in a more general Django context, independent of ``django-guardian``. That is described in the Django docs [here](https://docs.djangoproject.com/en/5.1/ref/contrib/auth/#anonymoususer-object).

Basically, `AnonymousUser` is a class defined in `django.contrib.auth.models`. The `AuthenticationMiddleware` attaches a user property to http requests as they pass through. If no User is logged in, then an instance `AnonymousUser` is attached to the request.

2024-10-16 18:42 UTC, jchate6 commented on docs/common/permissions.rst
> +When you first establish your TOM, ``django-guardian`` will create an ``AnonymousUser`` as the default user for the
I think if we want to add a section about `AuthenticationMiddleware` that's valid, but we should find a better place to put it.

Does it make sense to have a general page about the middleware generally? Or why certain things are set by default in `settings.py`?

At some point this feels like just teaching people Django, and there are better docs for that.

2024-10-22 20:54 UTC, phycodurus approved these changes

2024-10-23 16:39 UTC, merged