1019 add moon to aladin sky chart on target list page
TOMToolkit/tom_base pull request #1118
Opened 2024-11-13 23:56 UTC by phycodurus

Sending you this draft PR to keep you in the loop.

2024-11-15 01:02 UTC, phycodurus commented
This is ready for review now.
1. Uses Astropy for Sun, Moon position and Astroplan for Moon illumination
2. Sun, Moon data passed from inclusion tag to template via context
3. Moon icon greyscale is a function of Moon illumination
4. Also refactored Targets to be in a single Aladin catalog (vs. each target in its own catalog)

Looks like this:
![image](https://github.com/user-attachments/assets/b7c9c943-f976-461a-9135-926baf85e678)

2024-11-19 22:41 UTC, jchate6 requested changes
Have a few strong opinions about colors and symbol sizes that I think should be changed.

I also went ahead and just added the phase icons rather than making another 0 priority story to be lost in the icebox for years.

2024-11-19 22:41 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
> +    // get a unicode representation of the Moon based on illumination fraction
I went ahead and added the proper phase display code here.

2024-11-19 23:06 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
> +        {popupTitle: 'Geocentric Moon',
This should probably be "Moon (Geocentric)"

2024-11-19 23:06 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
> +        {popupTitle: 'Geocentric Sun',
Same as for moon.

2024-11-20 00:29 UTC, jchate6 approved these changes
Looks great!

2024-11-20 19:09 UTC, jchate6 requested changes
The things we discussed. Let me know if you'd like me to make these changes.

2024-11-20 19:09 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
>      for (var i = 0; i < targets.length; i++) {
This loop was important for letting people display or remove individual targets.

2024-11-20 19:09 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
> +    const moonImage = A.catalog({shape: drawMoon});
This should have a `name: 'Moon'` in the dictionary. My bad.

2024-11-20 19:09 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/aladin_skymap.html
> +    const moonImage = A.catalog({shape: drawMoon});
Also, can we add a `color: 'gray'` so the catalog tag in the stack menu is vaguely moon colored? It won't do anything to the moon image, but will make it distinct from the many targets.

2024-12-05 21:37 UTC, jchate6 approved these changes

2024-12-05 21:42 UTC, merged