Remove target input from form if its fixed, add ability to share targ…
TOMToolkit/tom_base pull request #1142
Opened 2024-12-19 00:13 UTC by jnation3406

…et and its existing data when creating a persistent share, remove download from the destinations list, and bold the service portion of destination string. I had to refactor where some methods were to get around circular imports.

Many of these come from comments from Andy yesterday when he saw the sharing page. Here is a screenshot of what it looks like now:
![image](https://github.com/user-attachments/assets/240f2986-4be6-4271-aed9-2ad36e69c263)

2024-12-19 18:22 UTC, jchate6 requested changes

2024-12-19 18:22 UTC, jchate6 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
This is silently breaking for me.
I'm getting back `b'{"message_text":["This field may not be null."],"submitter":["This field may not be blank."]}'`
Obviously these things need to be autofilled or use the other form.
It would also be nice if these made the same user facing alerts that normal sharing does (for success as well as failure.)

2024-12-19 18:22 UTC, jchate6 commented on tom_targets/templates/tom_targets/partials/create_persistent_share.html
> +      {% if not target %}
Like this change a lot.

2024-12-19 18:22 UTC, jchate6 commented on tom_targets/sharing.py
> +                                    )
missing a space before the parentheses here to make flake happy

2024-12-19 21:43 UTC, jnation3406 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
Thanks for checking that - I had thought submitter would be autoset by Hermes but it actually doesn't do that for outgoing messages, only incoming. So I've set the submitter to be the `TOM_NAME` which seems appropriate to me, and set the message text to be empty string instead of None.

2024-12-19 21:45 UTC, jnation3406 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
Also, the error should me mapped through now so it should stop the creation of a persistent share and show the error on screen if you have a problem when sharing all existing data. If it succeeds, nothing is shown but the persistent share is created and will show up, so that is the signal that it succeeded in sharing existing data too.

2024-12-20 21:38 UTC, jchate6 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
I'm still getting a silent failure for `HTTPError('400 Client Error: Bad Request for url: https://hermes-dev.lco.global/api/v0/submit_message/')
b'{"topic":["Hermes Dev can only submit to the hermes.test topic."]}'`

as well as missing telescope/instrument

2024-12-20 23:06 UTC, jnation3406 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
Hmm I'll look into the error not making it through... What do you mean by missing telescope/instrument though? Is it stored in your datums value dict as 'telescope' and 'instrument'?

2024-12-20 23:30 UTC, jchate6 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
yeah, not having the telescope/instrument in my data is just another way my hermes message can be rejected. The issue isn't that, it's just one of the two ways I tried to get errors back from hermes.

2024-12-20 23:40 UTC, jnation3406 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
Ah okay I understand what were saying now

2024-12-21 00:29 UTC, jnation3406 commented on tom_targets/sharing.py
> +def share_target_and_all_data(share_destination, target):
I've updated it again, and the errors are definitely coming through now! Sorry the error feedback handler stuff had me confused a bit.

2025-01-02 19:57 UTC, jchate6 approved these changes
Looks good. Thanks!

2025-01-07 01:32 UTC, merged