update TNS URL
TOMToolkit/tom_base pull request #413
Opened 2021-02-02 21:07 UTC by griffin-h

The Transient Name Server recently migrated their server to AWS, and now they have a new URL. See https://www.wis-tns.org/content/tns-newsfeed#comment-wrapper-20280 for more details.

I updated all instances of the wis-tns.weizmann.ac.il URL to www.wis-tns.org throughout the package.

2021-02-03 23:28 UTC, dmcollom requested changes
Thanks for noticing this and correcting it! Just looking for a quick stylistic change.

Also, are you having any issues using the module? I tried to make the base url change a while back, and (with a borrowed API key) wasn't able to successfully make any queries.

2021-02-03 23:28 UTC, dmcollom commented on tom_alerts/brokers/tns.py
> +tns_search_url = 'https://www.wis-tns.org/api/get/search'
So, ideally, to avoid code duplication, this would look a little more like this:

```
TNS_BASE_URL = 'https://www.wis-tns.org/'
TNS_OBJECT_URL = f'{TNS_BASE_URL}api/get/object'
TNS_SEARCH_URL = f'{TNS_BASE_URL}api/get/search'
```

This way, it only need to be changed in one place in the future. Constants in all caps is also Python convention.

2021-02-03 23:28 UTC, dmcollom commented on tom_alerts/brokers/tns.py
> +            url='https://www.wis-tns.org/object/' + alert['objname'],
Just out of curiosity, because I don't have a TNS API key to test this, is this the correct URL? The object url listed above is at `/api/get/object/`--just want to be sure.

2021-02-04 00:39 UTC, griffin-h commented on tom_alerts/brokers/tns.py
> +            url='https://www.wis-tns.org/object/' + alert['objname'],
Yes I think the idea here was to have the alert URL go to a human-readable page, rather than the API. For example, https://www.wis-tns.org/object/2020mot.

2021-02-04 00:40 UTC, griffin-h commented on tom_alerts/brokers/tns.py
> +tns_search_url = 'https://www.wis-tns.org/api/get/search'
Sounds good. I was just updating what was already there (which apparently I also wrote, so no wonder it's bad style), but I've fixed this now.

2021-02-04 00:45 UTC, griffin-h commented
> Also, are you having any issues using the module? I tried to make the base url change a while back, and (with a borrowed API key) wasn't able to successfully make any queries.

It seems to work for me, but maybe someone in the supernova group there can confirm?

2021-02-05 16:49 UTC, dmcollom approved these changes

2021-02-05 16:49 UTC, merged