Feature/MuSCAT support
TOMToolkit/tom_base pull request #468
Opened 2021-06-25 22:07 UTC by cjoldelo

All the proposed additions for MuSCAT support, as well as miscellaneous additions for comment.

2021-06-28 22:49 UTC, dmcollom commented
> @dmcollom When I run this test code, it returns the correct import error but still returns the test as failed. This morning you mentioned creating a fake response for the code to return; do I need to do that?
> Unittest mock traceback ex: https://docs.python.org/3/library/unittest.mock.html#quick-guide

@cjoldelo You're going to want to use [assertRaises()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) within another context manager. Essentially, this will fail the test *unless* an exception is raised.

2021-06-30 21:53 UTC, dmcollom commented
> @dmcollom I saw that my commit from a few days ago failed a publish_coverage test with the exception:
> 'coveralls.exception.CoverallsException: Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.'
> How can I resolve this exception?
> Thanks!

So (I believe) this is happening because your repo is a fork of ``tom_base``, and you need to set a Github secret value with the correct token. I will send you the token via Slack, and you should set the proper secret in your forked repo.

2021-07-08 18:45 UTC, cjoldelo commented
@dmcollom This Pull Request is ready for review!

2021-07-08 20:32 UTC, dmcollom requested changes

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +import unittest
In general, this test should live in `tom_base/tom_alerts/tests/tests.py`, and grouped in a more appropriate spot there, rather than just living on its own.

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +# env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
This should be removed.

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +# Test alert data. Normally this would come from a remote source.
If this test data isn't used, it should also be removed.

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +            with patch('tom_observations.api_views.get_service_class') as mock_get_service_class:
I'm a little unsure that this is testing the proper item. You're intending to test `tom_alerts.brokers.broker.get_service_class`, but this is patching `tom_observations.api_views.get_service_class`. This looks like a copy/paste job that should be corrected, and ensured to be testing the correct item.

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +#Failure to import module
So with tests, the proper way to comment is to put a string under the method signature, and then the test description will print out to console during a verbose run. For example in this case:

```python
def test_import_invalid_mod(self):
    """Test that attempting to import a nonexistent broker module raises an ImportError"""
    ...
```

Also, a couple _really_ nitpicky notes on that:
- Comments should be at the same depth as what they're commenting--so this one, which will ultimately be replaced by the string below the signature, would normally be indented to match `def test_import_valid_mod`
- Comments need a space between the octothorpe and the comment itself

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +class TestModuleImport(TestCase):
As kinda stated above, this should probably be consolidated with a more appropriate test class.

2021-07-08 20:32 UTC, dmcollom commented on test_attempt.py
> +                    mock_get_service_class()
Can you clarify what we're trying to test here, again? Because what it looks like is that you're creating a mock object, telling it to raise an Exception, and then calling it and making sure it raises the Exception. It doesn't look like this ever calls any real TOM Toolkit code, so it isn't really testing anything.

2021-07-08 20:43 UTC, cjoldelo commented on test_attempt.py
> +            with patch('tom_observations.api_views.get_service_class') as mock_get_service_class:
You're right that this is an incorrect copy/paste, though I don't even remember where I got the example from. It should be tom_alerts.alerts.get_service_classes, which I will change.

2021-07-08 20:51 UTC, cjoldelo commented on test_attempt.py
> +                    mock_get_service_class()
This is for two specific lines of code in the get_service_classes function in tom_alerts.alerts that Coveralls said wasn't tested. I thought I would start small for the unit testing. The lines of code are:
except (ImportError, AttributeError):
[indent] raise ImportError(f'Could not import {service}. Did you provide the correct path?')
I thought that in order to test the code, you just had to create an ImportError and see that the code returned what you told it to. Does the mocking mean that I worked around the problem rather than testing the actual code?

2021-07-08 23:18 UTC, dmcollom commented on test_attempt.py
> +                    mock_get_service_class()
Yeah, you did more or less work around the problem and not test the code. I think the patch line you copied is the one I used as an example.

If [this](https://coveralls.io/builds/40896872/source?filename=tom_alerts%2Falerts.py#L49) is the line of code you're testing, then you'd want to trigger [this line](https://coveralls.io/builds/40896872/source?filename=tom_alerts%2Falerts.py#L47) to raise the `ImportError`, and so I believe your patch should actually be `with patch('tom_alerts.alerts.import_module') as mock_import_module`, with the appropriate changes due to the variable renaming.

Something else you could do to enhance this is to add another subtest that raises an `AttributeError` instead, to ensure that it gets triggered in both cases. Also, you may consider testing that the message is what you expect, by passing a `msg` kwarg as shown [in the docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegex). That will ensure that you're actually getting into the code as expected.

2021-07-08 23:35 UTC, cjoldelo commented on test_attempt.py
> +                    mock_get_service_class()
Alright, I'll do my best to get to this tomorrow. Thank you, and sorry for all the hassle!

2021-07-12 16:18 UTC, cjoldelo commented on tom_alerts/tests/tests.py
> +@override_settings(TOM_ALERT_CLASSES=['tom_alerts.fake_broker'])
@dmcollom Let me know how you feel about the placement/if you have any more comments!

2021-07-13 16:52 UTC, dmcollom commented on tom_alerts/tests/tests.py
> +@override_settings(TOM_ALERT_CLASSES=['tom_alerts.fake_broker'])
That looks like a fine spot--I would just rename the class to ``TestAlertModule`` and the test itself to ``test_get_service_classes_import_error``, as those are more descriptive and closer to what's actually being tested. Otherwise, I think this can be un-drafted.

2021-07-13 16:52 UTC, dmcollom commented on tom_alerts/tests/tests.py
> +@override_settings(TOM_ALERT_CLASSES=['tom_alerts.fake_broker'])
Ah, there are a couple of linting things to be fixed, as well.

2021-07-13 18:02 UTC, cjoldelo commented on tom_alerts/tests/tests.py
> +@override_settings(TOM_ALERT_CLASSES=['tom_alerts.fake_broker'])
@dmcollom I think it should pass the lint now. I'm having trouble running the tests in tom_base on my own machine; something about the line endings in Windows and Unix not being the same. I'm looking into it now, but apologies in advance if the code still doesn't pass the lint.

2021-07-13 18:09 UTC, cjoldelo commented on tom_alerts/tests/tests.py
> +@override_settings(TOM_ALERT_CLASSES=['tom_alerts.fake_broker'])
I'm also still getting the Report Coverage issue from before, though I put in the Coveralls Repo Token you sent me: "Running on GitHub Actions but GITHUB_TOKEN is not set. Add GITHUB_TOKEN to your step config." Is this something to be concerned about?

2021-07-14 00:09 UTC, dmcollom approved these changes

2021-07-14 00:09 UTC, merged