Dev
TOMToolkit/tom_base pull request #471
Opened 2021-07-08 23:55 UTC by new2128

2021-07-09 17:37 UTC, new2128 commented
@dmcollom Can you review this pull request? Thank you!

2021-07-09 17:39 UTC, dmcollom requested changes

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
> +alert1 = {
Just in looking at the response for the object you're using for testing, it looks like [this](https://lasair.roe.ac.uk/object/ZTF18aaaduje/json/)

You don't need to copy/paste the entire 7000 lines of JSON, just a small subset of the data that's used by the code you're testing. However, I'm including this just to point out that `candidates` should be a `list`, not a `dict`.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/brokers/lasair.py
> +            name=str(alert.get('objectId')),
Good catch on this! Looks like Lasair has changed their API since this was written.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/brokers/lasair.py
> +            ra=alert['candidates'].get('ra'),
I would use the object-level `ramean` and `decmean` rather than the `ra`/`dec` from a single candidate of the object.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/brokers/lasair.py
> +            #galactic_lng=alert['objectData']['glonmean'],
Is there a reason you commented this out? The galactic latitude/longitude are useful data.

Also, if there's a valid reason, commented code really shouldn't be included in a final draft of a PR, unless there's an accompanying comment informing the reader why.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
> +    @mock.patch('tom_alerts.brokers.lasair.LasairBroker.fetch_alert')
I don't believe you need to do any patching, given that the `LasairBroker.fetch_alert` method isn't called by the `to_target` method that you're testing.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/tests.py
> -import json
This file absolutely should not be deleted.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
> +        created_target = LasairBroker().to_target(testalert) #uses to_target method
This happened to Claire as well, but for some reason the Github linter isn't catching that in-line comments need two spaces between the code and the octothorpe, and one space between the octothorpe and the text. Have you been able to run `flake8 tom_* --exclude=*/migrations/* --max-line-length=120` locally?

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
> +        testalert = alert1
Because the content of `alert1` isn't modified by `to_target`, there's really no need to assign it to an intermediary variable.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
> +    def test_to_target(self, alert):
You're going to wind up removing `alert` as an arg in the method signature when you remove the `patch`, but in the future, I would prefer a more descriptive argument name. Something like `mock_fetch_alert`.

2021-07-09 17:39 UTC, dmcollom commented on tom_alerts/tests/brokers/test_lasair.py
You _might_ consider also testing the other values assigned in `to_target`, like `meanra`/`meandec`. I realize that they're simple assignments, but if that code changes in the future, the test acts as a trigger to force the tests to be updated, and also kind of as a canary in the coal mine to ensure that data is still getting assigned properly.

2021-07-09 17:39 UTC, dmcollom commented on tom_observations/tests/facilities/test_gemini.py
> +from django.test import TestCase
This is very much an arbitrary style thing, but at LCO we tend to group imports in three sections, each alphabetized and separated by a newline:

- Python built-in imports (`json`, `unittest.mock`)
- Third-party installed modules (`django.test`)
- Project-level imports (`tom_common.exceptions`, `tom_observations.facilities.gemini`)

2021-07-09 17:39 UTC, dmcollom commented on tom_observations/tests/facilities/test_gemini.py
> +
Again something that should be caught by linting, but there should only be one newline between the class definition and the first method definition.

2021-07-09 17:39 UTC, dmcollom commented on tom_observations/tests/facilities/test_gemini.py
> +'''
Class description comments should go just below the class definition, and be indented. Example: https://github.com/TOMToolkit/tom_base/blob/b8abfd8fd00bf62220555602370f46f698a1b6c0/tom_targets/models.py#L38

2021-07-21 20:09 UTC, new2128 commented
@dmcollom I've finished editing, can you review this pull request again?

2021-07-27 17:11 UTC, dmcollom requested changes
Looks great! Just the one change, and then I'll approve/merge it, and I promise I'll be quicker this time.

2021-07-27 17:11 UTC, dmcollom commented on tom_alerts/brokers/lasair.py
> +            name=str(alert.get('objectId')),
Casting this to a string is superfluous, as the format of the objectId is `ZTF##???????`. Did you run into issues that necessitates this?

2021-07-27 20:28 UTC, dmcollom approved these changes

2021-07-27 20:42 UTC, merged