add absolute magnitude axis to photometry plot
TOMToolkit/tom_base pull request #569
Opened 2022-10-14 21:30 UTC by griffin-h

This adds an absolute magnitude axis to the photometry plot on the target detail page, if the target distance is populated. I could not find a way to add a secondary y-axis with a fixed offset from the primary y-axis in Plotly, so I had to add some code that manually scales the axis based on the data. I also had to move the legend to the top of the plot so that it doesn't overlap with the new tick labels.

2023-02-02 20:37 UTC, jchate6 requested changes

2023-02-02 20:37 UTC, jchate6 commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +            all_ydata.append(np.array(filter_values['magnitude']) - np.array(filter_values['error']))
These will break for any malformed data (Data with Nonetype in the error or Mag) that exist in the DB. 
You're also translating types here, so you might want to set the array type to `float64` to make sure it gets handled correctly.

2023-02-02 20:37 UTC, jchate6 commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +            all_ydata.append(filter_values['limit'])
Limit could also theoretically contain `None` values.

2023-02-02 20:37 UTC, jchate6 commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +            'side': 'right',
you need to include a `'zerolinecolor': 'rgba(0,0,0,0)',` here to remove the "zero" line added if absmag ever goes positive (you know, for people who look at things that are ACTUALLY 10 pc away :D).

2023-02-02 22:44 UTC, griffin-h commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +            'side': 'right',
Hah I literally never would have considered absolute magnitudes (or apparent magnitudes) close to zero. I just turned the lines off with `'zeroline': False`.

2023-02-02 22:46 UTC, griffin-h commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +            all_ydata.append(np.array(filter_values['magnitude']) - np.array(filter_values['error']))
By forcing the dtype to `float`, any `None` values will get converted to `nan`, which I then ignore using `np.nanmax` and `np.nanmin`.

2023-02-02 23:30 UTC, jchate6 requested changes

2023-02-02 23:30 UTC, jchate6 commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +        dm = 5. * (np.log10(target.distance) + 5.)  # assumes target.distance is in Mpc
So, the `Distance` stored in the DB is in parsec according to all the Help text and documentation.

See `tom_targets.models` line 198.

2023-02-02 23:36 UTC, jchate6 commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +        dm = 5. * (np.log10(target.distance) + 5.)  # assumes target.distance is in Mpc
There are ways to store unit information in a django table, but that's probably beyond the scope of this PR.

2023-02-02 23:42 UTC, griffin-h commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +        dm = 5. * (np.log10(target.distance) + 5.)  # assumes target.distance is in Mpc
I agree it's beyond this PR, but it would be nice to be able to choose different units, even if it's just a global setting for your TOM. Extragalactic people will definitely assume all distances are in Mpc if they don't read the documentation.

2023-02-03 00:04 UTC, jchate6 approved these changes
Looks good!

2023-02-03 00:07 UTC, merged