Share Photometry
TOMToolkit/tom_base pull request #572
Opened 2022-10-20 21:31 UTC by jchate6

Allow for publishing photometry to Hermes or sharing directly with another TOM.

2022-10-22 00:09 UTC, jchate6 commented
Sharing Datums:

- [ ] get data for selected points in plot (selection event)
- [ ] create form table with selected points
- [ ] route form similar to data products form.

2022-11-17 16:35 UTC, jchate6 commented
get username:
1. Log into Scimma Auth
2. Try to create a group
3. read error message at top of screen

2022-12-15 19:48 UTC, phycodurus commented on tom_base/settings.py
> +        'API_TOKEN': os.getenv('HERMES_API_TOKEN', 'set HERMES_API_TOKEN value in environment'),
don't forget to add a `TOPICS` key and value here.
Also, SCiMMA Auth username and scram creds proabaly need to go here as well

2022-12-15 20:18 UTC, phycodurus commented on tom_dataproducts/templatetags/dataproduct_extras.py
> +def get_data_sharing_destinations():
yes, this could be remove in favor of `forms.py::get_sharing_destination_options()`

2022-12-16 17:09 UTC, jchate6 commented on tom_dataproducts/alertstreams/hermes.py
> +def get_hermes_topics():
@phycodurus Should we keep this, or remove it?

2022-12-16 18:24 UTC, jchate6 commented on tom_dataproducts/views.py
> +        return redirect('/')
I tend to redirect to the home page after this because I think that's how it was in your original function, is that best? 
Would it be less surprising to just "redirect" to a refreshed target page?

2023-01-04 21:12 UTC, phycodurus approved these changes

2023-01-10 05:01 UTC, jnation3406 requested changes
Just a few schema changes to make to line up with current hermes schemas.

2023-01-10 05:26 UTC, jchate6 commented on tom_dataproducts/alertstreams/hermes.py
> +        table_row['brightness'] = datum.value['limit']
nothing is guaranteed. We do no validation on value. I should make that a `get`.

2023-01-10 05:27 UTC, jchate6 commented on tom_dataproducts/models.py
> +    message = models.ManyToManyField(AlertStreamMessage)
Yes, in theory we want a "message" for each topic the datum is sent to. It's also possible that the same datum could be sent multiple times in different contexts.

2023-01-10 05:28 UTC, jchate6 commented on tom_dataproducts/models.py
> +    message = models.ManyToManyField(AlertStreamMessage)
Or received from multiple sources, and you might want to have a handler just add a message for the datum, and not make a new datum.

2023-01-10 06:27 UTC, jchate6 commented on tom_dataproducts/alertstreams/hermes.py
> +                'source_location': 'HERMES',
I'm not even sure how this particular piece of information is used...

2023-01-11 22:32 UTC, merged