tom_alerts changes for more general Brokers (specifucally `tom_hermes`)
TOMToolkit/tom_base pull request #639
Opened 2023-04-24 18:53 UTC by phycodurus

The `tom_hermes` Broker defines queries that return a list NonLocalizedEvents, not Targets as with other Brokers).
This PR allows Brokers to tell `tom_alerts` more specifically how to behave:
1. Adds a hook allow the Broker to specify the template to use to display query results and create objects from the results. (`query_result.html`, conventionally)
2. Add a hook to allow the Broker to add data to the `context` data sent to the query result template.

2023-04-24 20:39 UTC, jchate6 commented on tom_alerts/brokers/hermes.py
> +                instructions <a href="https://github.com/TOMToolkit/tom_hermes">here</a>.
This github link contains no Readme or instructions.

2023-04-24 20:45 UTC, jchate6 requested changes
We need to update the docs in a few places to accommodate these changes.
See: 
`docs.brokers.index:line18`
`docs.api.tom_alerts.brokers:line36-50`
`docs.api/plugins:line61`

We'll also want to add the description of the template name in `docs.brokers.create_broker`.

2023-04-24 23:54 UTC, phycodurus commented on tom_alerts/brokers/hermes.py
> +                instructions <a href="https://github.com/TOMToolkit/tom_hermes">here</a>.
I've update the [tom_hermes/README.md](https://github.com/TOMToolkit/tom_hermes/blob/dev/README.md)

2023-04-26 21:48 UTC, jchate6 approved these changes

2023-04-26 22:58 UTC, merged