Let Facility modules specify a custom template and add context_data
TOMToolkit/tom_base pull request #652
Opened 2023-05-10 20:04 UTC by phycodurus

2023-05-11 01:40 UTC, jchate6 requested changes
This has some breaking tests.

2023-05-11 15:28 UTC, jchate6 requested changes

2023-05-11 15:28 UTC, jchate6 commented on tom_observations/views.py
> +        facility_context = facility_class().get_facility_context_data()
This line breaks the tests.

2023-05-12 17:06 UTC, phycodurus commented on tom_observations/views.py
> +        facility_context = facility_class().get_facility_context_data()
ack! was passling locally, but PR was missing the commit below

2023-05-12 18:02 UTC, jchate6 approved these changes
looks good now

2023-05-12 18:54 UTC, merged