Add ability to navaigate to specific tab in target view.
TOMToolkit/tom_base pull request #701
Opened 2023-10-18 18:51 UTC by davner

Resolves Issue #697.

1. Introduces URL parameter support for directly navigating to specific tabs in the target detail view (e.g., `/targets/1/?tab=observations`). Initial implementation is limited to two sections that our users found most impactful but could be applied anywhere the directs to the target detail view. This was written with vanilla javascript, removing the concern of Jquery conflicts. 
  
2. Augments `observation_list.html` to display observation IDs, improving user experience to trace data to what ID in the overview.

2023-11-18 01:46 UTC, jchate6 requested changes
I really like these features, and I think this new functionality is fantastic, but I don't see how this directly addresses Issue #697. 
The active tab information is still lost on refresh, correct? 
Does this functionality override that issue, or should the issue persist once this PR is merged?

2023-11-18 01:46 UTC, jchate6 commented on tom_observations/templates/tom_observations/partials/observation_list.html
> +      <td>{{ observation.observation_id }}</td>
What do you think of replacing this line with
```
{% if observation.url %}
  <td><a href="{{ observation.url }}">{{ observation.observation_id }}</a></td>
{% else %}
  <td>{{ observation.observation_id }}</td>
{% endif %}
```
So that this can be a direct link to the data source if it has one?

2023-11-18 03:25 UTC, davner commented
@jchate6 , you've raised a valid point. The problem still persists, as this PR provides enhancements, but doesn't address the original issue. I've given this some thought and have something. I do want to avoid local storage because I don't want the tab to persist upon navigating away. 

1. Event Listener on Tabs: I will add an event listener to the tabs.
2. URL Update on Tab Click: When a tab is clicked, the URL will be updated to reflect the active tab. This ensures the user stays on the same tab after certain actions.
3. Page Refresh Behavior: Refreshing the page will take the user back to the last active tab, as indicated by the URL.
4. No Local Storage Dependency: We won't use local storage, so the last opened tab won't persist if the user navigates away. This keeps the experience clean and straightforward.
5. Specific Tab Redirects: The solution still allows for redirecting to a specific tab when needed.

Our URLs would look like
http://localhost:8000/targets/1/?tab=manage-datahttp://localhost:8000/targets/1/?tab=manage-groups
etc when the user clicks on a tab. Then if refreshed the correct tab persists. 


Thoughts?

2023-11-18 03:26 UTC, davner commented on tom_observations/templates/tom_observations/partials/observation_list.html
> +      <td>{{ observation.observation_id }}</td>
Yes, this is a great idea!

2023-11-18 03:41 UTC, jchate6 commented
Avoiding local storage makes a lot of sense. 
I agree that an event listener on the tab is the way to go. 
Thanks!

2023-11-21 00:17 UTC, davner commented
@jchate6 Comments have been addressed and tab is remembered on reload.

2023-11-21 03:56 UTC, jchate6 commented
Thanks @davner! I probably won't get to this until Monday.

2023-11-27 22:58 UTC, jchate6 approved these changes
This is great.
Thanks for this @davner.
I think we'll probably want to take some time in the future changing redirects and maybe adding a default option to `settings.py` so users can choose their default landing page for their TOM. Very exciting.

2023-11-27 22:59 UTC, merged

2023-11-28 17:57 UTC, davner commented
@jchate6 Not a problem. I'm trying to push back all the changes I make for our project that would be beneficial to all users. Glad you like this one!