Feature/install poetry
TOMToolkit/tom_base pull request #718
Opened 2023-10-26 01:33 UTC by phycodurus

We should consider widening the requirements on the dependencies listed in the pyproject.toml file

2023-10-26 15:12 UTC, jchate6 requested changes
I strongly disagree with how these have been done. I think we need as broad a range of dependencies as possible, especially if we plan to support currently supported versions of python. (3.8 has security support for another year).

Also, the original motivation for including poetry was specifically to allow us to increase our compatibility with more versions of astropy and numpy. This was a request from our largest user and should probably at least be considered in this PR.

2023-10-26 15:12 UTC, jchate6 commented on pyproject.toml
> +astropy = "^5.3.4"
This is incompatible with python 3.8

2023-10-26 15:13 UTC, jchate6 commented on pyproject.toml
> +python = "^3.9"
If we are doing this, we should remove the tests for 3.8

2023-10-26 17:51 UTC, jchate6 commented on pyproject.toml
> +astropy = "^5.3.4"
noted ;)

2023-10-27 22:13 UTC, jchate6 commented
https://nsf-noirlab.gitlab.io/csdc/antares/client/installation.html:
```Note
Python 3.10 Prerequisites

librdkafka is required to install antares-client with python 3.10

Mac: brew install librdkafka

Ubuntu: apt-get install librdkafka-dev

2023-10-27 22:43 UTC, jchate6 commented
Library on github:
https://github.com/confluentinc/librdkafka

2023-10-30 23:07 UTC, jchate6 commented on poetry.lock
> +confluent_kafka = "1.7.0"
This is the restriction that's incompatible with Python >3.9

2023-10-30 23:08 UTC, jchate6 commented on poetry.lock
> +antares-client = ">=1.4,<2.0"
This is the dependency that we include that leads to the 3.10 incompatability.

2023-10-30 23:09 UTC, jchate6 commented on poetry.lock
> +antares-client = ">=1.4,<2.0"
antares_client requires a version of confluent_kafka that requires a c++ package to be compatible with python >3.9

2023-10-30 23:31 UTC, jchate6 commented
`pip install tom-antares==1.2.6` Gets me the following:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tom-alertstreams 0.5.1 requires hop-client<0.8,>=0.7, but you have hop-client 0.8.0 which is incompatible.
Successfully installed antares-client-1.4.0 confluent_kafka-1.7.0 tom-antares-1.2.6

2023-10-31 21:33 UTC, jchate6 approved these changes
Very exciting to have this, Do we need to update documentation for not having tom_antares anymore?

Also, do we need to make an issue in tom_antares to handle the dependency fallout that will no doubt occur there?

2023-10-31 21:33 UTC, jchate6 commented on .github/workflows/run-tests.yml
> +        python-version: "3.9" # for antares-client's confluent-kafka dependency
This is technically now for numpy not playing nice with 3.12?

2023-10-31 21:57 UTC, phycodurus commented on .github/workflows/run-tests.yml
> +        python-version: "3.9" # for antares-client's confluent-kafka dependency
exactly

2023-10-31 22:02 UTC, merged