715 pan starrs forced photometry
TOMToolkit/tom_base pull request #743
Opened 2023-11-14 14:39 UTC by phycodurus

Add PanSTARRS PS1 forced photometry service class, MAST client library (panstarrs_api.py), and data processor.

This is a draft while I add some error checking, but comments are welcome.

2023-11-14 19:23 UTC, jchate6 requested changes
All of this needs to be much more explicitly defined in the documentation.
[This section](https://tom-toolkit.readthedocs.io/en/stable/managing_data/forced_photometry.html#integrating-existing-forced-photometry-services) has code blocks that do not show up correctly in the live docs. 

I'd also like to see a list of currently built in Forced Photometry services with details about each specific one including links to the API and description of features.

Finally, I think `Query Forced Photometry Service` section on the Target Detail page's Manage Data Tab should be under the data table and either needs to be hidden if no services are available, or should include a blurb below it saying something like "Forced Photometry has not been initialized. Please see the [documentation](https://tom-toolkit.readthedocs.io/en/latest/managing_data/forced_photometry.html) for details."

2023-11-14 22:31 UTC, jnation3406 requested changes
Some comments, biggest change being you probably should use the task setup for the main logic of querying panstarrs so it can happen asynchronously for the user (even though it is a single synchronous query).

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/forced_photometry_service.py
> +logger.setLevel(logging.DEBUG)
I assume you mean to remove this...

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +    # )
Did you want to do this the same way as the atlas form, where its an either/or for a datetimepicker or raw mjd input? You should be able to copy that code from the atlas form...

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +        # TODO: get these from panstarrs_api.py
You already did this TODO right?

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +    # TODO: get these from panstarrs_api.py
and this one as well.

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +    # )
Oh i see you prefill in the mjd so you wouldn't know which input the user intends to use I guess without some more code.

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +            raise forms.ValidationError("Please specify the maximum date in either datetime or mjd format")
Yeah, this was for the atlas form that had two options for inputting date, to make sure that only one option was used for each field.

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +            max_date_mjd = Time(query_parameters.get('max_date')).mjd
Since you aren't using a min_date/max_date field, this code should be removed.

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +        if len(response.content) == 0:
Unless this always responds nearly instantly (which I assume it doesn't for large date ranges), then you should probably still do this in the same exact way as the Atlas query, making it a task that is callable directly if no dramatiq is setup, or calling it asynchronously if dramatiq is present. This way, if the user has dramatiq setup, they will not have to sit waiting (and potentially navigate away breaking things) when making a large query. Instead, it will return back to them immediately and they can continue working until the query is done and data is available.

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/templates/tom_dataproducts/partials/dataproduct_list_for_target.html
> +      <td><a href="{{ product.data.url }}" target="_blank">{{ product.get_file_name }}</a></td>
what is this needed for?

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs_api.py
> +        ]
this could just be an if/else setting choices either way?

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs_api.py
> +logger.setLevel(logging.DEBUG)
Don't forget to remove this

2023-11-14 22:31 UTC, jnation3406 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs_api.py
> +            'PANSTARRS', {}).get('url', 'https://catalogs.mast.stsci.edu/api/v0.1/panstarrs/')
Should the default url just be in the settings.py? and all this code just to return your fixed value doesn't seem great. If the user doesn't have a PANSTARRS section then they shouldn't be able to get a url right? I would think they should just not be able to submit a panstarrs query in that case...

2023-11-28 14:29 UTC, phycodurus commented on tom_dataproducts/templates/tom_dataproducts/partials/dataproduct_list_for_target.html
> +      <td><a href="{{ product.data.url }}" target="_blank">{{ product.get_file_name }}</a></td>
I thought the href-ed data product should open in a new browser tab.

2024-02-20 17:13 UTC, phycodurus commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +        if len(response.content) == 0:
#848

2024-02-24 01:03 UTC, jchate6 requested changes
We should handle an undefined DATA Product type more gracefully.
Currently the code crashes if an unknown dataproduct type is referenced from the target detail page:
`tom_base/tom_dataproducts/views.py", line 158`
`tom_base/tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py", line 189`

2024-02-24 01:03 UTC, jchate6 commented on tom_dataproducts/templates/tom_dataproducts/forced_photometry_form.html
> +    at RA {{ target.ra|floatformat:4 }}, DEC {{ target.dec|floatformat:4 }}</h4>
If it isn't going to be a form field, we need to include radius here. Preferably in arcmin or arcsec.

2024-03-18 21:49 UTC, phycodurus commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs_api.py
> +def get_default_columns(catalog='mean'):
for the moment, we'll be limiting queies to the Mean object catalog

2024-03-18 21:51 UTC, phycodurus commented on tom_dataproducts/processors/panstarrs_processor.py
> +                    mag_err_col_name = f'{optical_filter}MeanPSFMagErr'
At the moment, we will only support queries to the Mean object catalog. The 'Stacke object' catalog is not yet available through this form.

2024-03-19 16:52 UTC, phycodurus commented on tom_dataproducts/templates/tom_dataproducts/forced_photometry_form.html
> +    at RA {{ target.ra|floatformat:4 }}, DEC {{ target.dec|floatformat:4 }}</h4>
see Issue #880

2024-03-19 17:06 UTC, jchate6 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +
need an extra blank line here

2024-03-19 17:20 UTC, phycodurus commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +        min_date_mjd = query_parameters.get('min_date_mjd')
#881

2024-03-19 19:13 UTC, jchate6 commented on tom_dataproducts/processors/panstarrs_processor.py
> +class PanstarrsProcessor(DataProcessor):
This is caused by different csv files for the Data Products. So this is also true if I pull DR1 vs DR2

2024-03-19 19:18 UTC, jchate6 commented on tom_dataproducts/forced_photometry/panstarrs_service/panstarrs.py
> +        dp, created = DataProduct.objects.get_or_create(
I'll also point out that this breaks when trying to run forced photometry for different targets with the same date range.

2024-03-26 01:19 UTC, jchate6 approved these changes

2024-03-26 01:22 UTC, merged