Updated getting-started doc; included make-tom script
TOMToolkit/tom_base pull request #798
Opened 2023-12-22 23:04 UTC by rachel3834

Added information on the make-tom script and generally updated the getting-started page.

2023-12-23 00:22 UTC, jchate6 commented on docs/conf.py
> +    'sphinx_panels'
This is required for link buttons.
It needs to be added to `pyproject.toml`

2023-12-23 00:35 UTC, jchate6 requested changes
I've taken care of the dependencies, and made a few suggestions.

2023-12-23 00:35 UTC, jchate6 commented on docs/introduction/getting_started.rst
> +If you prefer to build your own system, here's how.
maybe reword to "build your system manually". 
This kinda implies that the results of make-tom aren't yours or aren't customizable.

2023-12-23 00:35 UTC, jchate6 commented on docs/introduction/getting_started.rst
> +You can run it first of all directly on your local machine using the
maybe change this to "You can run it immediately, directly on your local..."

2024-01-03 23:32 UTC, rachel3834 commented on docs/introduction/getting_started.rst
> +If you prefer to build your own system, here's how.
OK fair enough, I've changed the wording

2024-01-03 23:33 UTC, rachel3834 commented on docs/introduction/getting_started.rst
> +You can run it first of all directly on your local machine using the
Updated wording

2024-01-04 04:04 UTC, jchate6 approved these changes
excellent

2024-01-04 04:05 UTC, merged