Enhancement to the TNS broker to fetch classification
TOMToolkit/tom_base pull request #842
Opened 2024-02-13 19:18 UTC by KKruszynska

While developing the Microlensing Observing Platform, our customized version of the TOM Toolkit, I realized that it would be beneficial to grab a name and class from TNS (we use it mostly for classification). 

I think this might be useful for other TOM Toolkit users, but there are two issues with it that I am not sure how to solve:
-  the way the function runs now creates a TNS time-out when I run it for a large number of sources,
- I created a unit test for the new function, but it requires a TNS bot API key (in my local set-up, I use MOP's bot TNS API key). 

I would be happy to receive feedback on how to improve the new functionality to make it usable for other teams.

2024-02-15 17:17 UTC, jchate6 requested changes
We can't have normal unit tests that directly hit the outside world.
The purpose of these unit tests is to test the internal TOM Toolkit code, and we don't want to spam external services when running normal tests.

We have Canary tests that are run less frequently that hit the external services to make sure everything is behaving as expected with those connections.

For this purpose, You'll want to override settings with a fake API token, and mock the response from TNS.

See `TestLasairBrokerClass` in `tom_alerts.tests.brokers.test_lasair` for an example.
You can also use the `responses` package to spoof specific external calls.
See `test_share_dataproduct_no_valid_responses` at `tom_dataproducts.tests.test:568` for an example of how that works.

2024-02-15 18:37 UTC, KKruszynska commented
Thank you, I will adjust the unit test accordingly.

2024-02-16 00:05 UTC, jchate6 commented
I'll take a more in-depth look at this soon to see if there is some way to use the existing code or a minor re-factor of the existing code to accomplish your purpose here.

2024-02-16 21:36 UTC, jchate6 requested changes
Let me know if this makes sense, or if you need any help to implement this.
You might also want to take a look at `tom_catalog.harvesters.tns.TNSHarvester` to see if this already does some of what you want.

2024-02-16 21:36 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +        data = {
I don't think this is the place for this code. 
What I think would be better is to pull out the relavent parts of the above code into one or 2 additional functions.
Use these new functions to return the most useful product and then access and parse these results in your own custom Code for your TOM.

i.e., create a `fetch_tns_transients` that includes lines 126-140 above and is plugged into the appropriate locations and also `get_tns_object_info` that includes lines 143-152 above.

2024-02-29 00:03 UTC, KKruszynska commented on tom_alerts/brokers/tns.py
> +        data = {
Hi Joey, I changed the code to reflect that. I tested it and it seems to work, but I commented the unit test because it requires a response from the TNS server.

2024-02-29 21:51 UTC, jchate6 requested changes

2024-02-29 21:51 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +    # @classmethod
You should clean up these commented sections.

2024-02-29 21:51 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +        data = {
nice. Now move `fetch_tns_transients` above `fetch_alerts` and replace lines 131->152 with the line 
```
transients = cls.fetch_tns_transients(parameters)
```

2024-02-29 21:51 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +    def get_tns_object_info(cls, parameters):
The same exact thing you did above for pulling out `fetch_tns_transients` from `fetch alerts`, I'd like you to do again with this code.

2024-02-29 21:51 UTC, jchate6 commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
I agree that this test isn't super useful. I think we should probably remove this whole file until we write some dedicated canary tests.

If you want, it would be helpful to mock the response (like you did above) and make sure we are handling the alerts correctly.

2024-02-29 23:55 UTC, KKruszynska commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
I wanted to but fetch_alerts, detch_tns_transients and get_object_info are making queries to TNS and I have no way of intercepting the signal and putting in a mock response. I will remove this file.

2024-03-01 00:04 UTC, jchate6 commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
You can intercept those calls with the `responses` package.
https://github.com/getsentry/responses

2024-03-01 00:04 UTC, jchate6 commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
but it's OK to ignore that for now.

2024-03-01 00:09 UTC, KKruszynska commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
Inside the function?

2024-03-01 00:18 UTC, jchate6 commented on tom_alerts/tests/brokers/test_tns.py
> +# class TestClassSN(TestCase):
Yes. Take a look [here](https://github.com/TOMToolkit/tom_base/blob/90adda925cdd2d6d8e1c6480be4dc5b486cc8c9c/tom_dataproducts/tests/tests.py#L567) for an example of how we use it in a different part of tomtoolkit.

2024-03-08 01:07 UTC, jchate6 requested changes

2024-03-08 01:07 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +    def fetch_tns_transients(cls, parameters):
Can you add a docstring here describing what is expected for parameters?

2024-03-08 01:07 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +        if parameters['days_ago'] is not None:
`days_ago` and `min_date` might also not exist in parameters, similar to the values below.
If these are enforced, you might want to use a `try...except` to pass back some kind of error.

2024-03-08 01:07 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +    def get_tns_object_info(cls, parameters):
A similar doc string here. 
Remember Parameters here doesn't have to be the same as above, but it does need to contain a key called "objname".

2024-03-11 18:49 UTC, KKruszynska commented on tom_alerts/brokers/tns.py
> +    def fetch_tns_transients(cls, parameters):
done!

2024-03-11 20:10 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +    """
Something weird with the indent here...

2024-03-12 18:02 UTC, jchate6 approved these changes
Looks great, just one little doc comment.

2024-03-12 18:02 UTC, jchate6 commented on tom_alerts/brokers/tns.py
> +                and search radius and search radius unit (str), or
looks like these can be either `"arcsec"`, `"arcmin"`, or `"deg"`

2024-03-12 21:42 UTC, KKruszynska commented on tom_alerts/brokers/tns.py
> +                and search radius and search radius unit (str), or
added

2024-03-12 21:54 UTC, jchate6 approved these changes
Looks Great! Thanks for all of the work!

2024-03-12 21:55 UTC, merged