allow for DATA_PRODUCT_TYPES to be empty
TOMToolkit/tom_base pull request #874
Opened 2024-03-14 22:37 UTC by jchate6

This change allows for users to not include any `DATA_PRODUCT_TYPES` in their `settings.py`.
If none are found, then spectroscopy and photometry types are added.

The tests will break if the settings are actually blank because they reference settings directly, but this is not actually diagnostic of the code itself as much as the tests, and we actually want to test instances where `DATA_PRODUCT_TYPES` are set.

2024-03-15 21:29 UTC, phycodurus approved these changes
more breadcrumbs will be appreciated by our six-months from now selves.

2024-03-18 18:04 UTC, phycodurus requested changes

2024-03-18 18:04 UTC, phycodurus commented on tom_dataproducts/models.py
> +        for dp_values in DATA_TYPE_OPTIONS:
by saying `for dp_type_value, dp_type_name in DATA_TYPE_THINGS` the `dp_values[0]` would become `dp_type_value` which makes explicit what the first element of the tuple actually is.

2024-03-18 18:04 UTC, phycodurus commented on tom_dataproducts/models.py
> +        return data_product_type_dict[self.data_product_type][1]
again, if indexing into the tuple can be made more explicit as to what that value actually is, then that reduces the cognitive load on the reader.

2024-03-18 18:04 UTC, phycodurus commented on tom_dataproducts/models.py
> +        for dp_values in DATA_TYPE_OPTIONS:
ditto. see comments above.

2024-03-18 18:14 UTC, phycodurus commented on tom_dataproducts/models.py
> +        for dp_values in DATA_TYPE_OPTIONS:
yes, makes sense to use `_` for the unused value, but I don't think `dp_values` describes what that loop-variable represents. Something like `dp_choice_text` or `dp_type_choice_text` would be more descriptive.

2024-03-18 18:19 UTC, phycodurus commented on tom_base/settings.py
> +# This is a dictionary of tuples, with the first element being the type name and the second being the display name.
thank you. I think referencing `Field.choices` make sense and explains _why_ the first and second elements of the tuple are what they are.

2024-03-18 18:29 UTC, phycodurus commented on tom_setup/templates/tom_setup/settings.tmpl
> +# This is a dictionary of tuples, with the first element being the type name and the second being the display name.
see comment above wrt `Field.choices`

2024-03-18 18:29 UTC, phycodurus approved these changes

2024-03-18 18:30 UTC, jchate6 commented on tom_dataproducts/models.py
> +        for dp_values in DATA_TYPE_OPTIONS:
I'm going with `dp_type` to mimic other usage

2024-03-18 18:48 UTC, merged